source/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
 * List all routes and info with "php artisan route:list" or "php artisan route:list" <-------
 * https://stackoverflow.com/questions/25290229/laravel-named-route-for-resource-controller
 */


/* root route */
Route::get('/', function () {
    return view('welcome');
})->name('welcome');

/* to test stuff really quick... */
Route::get('/test', function () {
    return view('tests.index');
})->name('test');


/*
 * Auto generated routes for login, register, password
 */
Auth::routes();


/*
 * GROUP all the routes that requires authentication
 */
Route::middleware(['auth'])->group(function () {

    /* Start of an idea to control usage of mobile vs desktop design, using a Controller */
    Route::get('home', 'PageController@home')->name('home');

    /*
     * Admin stuff
     */
    Route::get('admin', 'AdminController@index')->name('admin.index');
    Route::post('admin/dumpDb', 'AdminController@runDbDump')->name('admin.dumpDb');
    Route::post('admin/dumpDbTables', 'AdminController@runDbTablesDump')->name('admin.dumpDbTables');
    Route::post('admin/clearCache', 'AdminController@clearCache')->name('admin.clearCache');
    //Route::get('admin/downloadFile/{path}', 'AdminController@downloadFile')->where('path', '.*')->name('admin.downloadFile');
    Route::get('admin/downloadFile', 'AdminController@downloadFile')->name('admin.downloadFile');
    Route::post('admin/clearBackups', 'AdminController@clearBackups')->name('admin.clearBackups');

    /*
     * nodes
     */
    Route::get('nodes/create', 'NodeController@create')->name('nodes.create');
    Route::get('nodes/{id}', 'NodeController@show')->name('nodes.show');


    /*
     * to-do list
     */
    Route::resource('todos', 'TodoController');
    Route::get('todos/done/{todo}', 'TodoController@done')->name('todos.done');
    Route::get('todos/undone/{todo}', 'TodoController@undone')->name('todos.undone');

    /*
     * websites
     */
    // ui endpoint for main page
    Route::get('websites', 'WebsiteController@index')->name('websites.index');
    // json api used in ajax todo: move to api routes?
    Route::post('websites', 'WebsiteApiController@create')->name('websites-api.create');
    Route::put('websites/{id}', 'WebsiteApiController@update')->name('websites-api.update');
    Route::delete('websites/{id}', 'WebsiteApiController@delete')->name('websites-api.delete');
    Route::get('websites/group/{group}', 'WebsiteApiController@group')->name('websites-api.read-group');

    /*
     * websiteGroups
     */
    Route::post('websiteGroups', 'WebsiteGroupController@store')->name('websiteGroups-api.create');
    Route::post('websiteGroups/position', 'WebsiteGroupController@updatePosition')->name('websiteGroups-api.position');
    Route::put('websiteGroups/{websiteGroup}', 'WebsiteGroupController@update')->name('websiteGroups-api.update');
    Route::delete('websiteGroups/{websiteGroup}', 'WebsiteGroupController@destroy')->name('websiteGroups-api.delete');

    /*
     * projects
     */
    Route::get('projects/{project}', 'ProjectController@show')->name('projects.show');
    Route::get('projects', 'ProjectController@index')->name('projects.index');

    /*
     * notes
     */
    Route::resource('notes', 'NoteController');
});

source/app/Todo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Todo
 *
 * @property int $id
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property string $content
 * @property string|null $done_date
 * @property int|null $priority
 * @property int|null $difficulty
 * @property int|null $weight
 * @property int|null $category
 * @property int|null $project
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Todo newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Todo newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Todo query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Todo whereCategory($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Todo whereContent($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Todo whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Todo whereDifficulty($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Todo whereDoneDate($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Todo whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Todo wherePriority($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Todo whereProject($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Todo whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Todo whereWeight($value)
 * @mixin \Eloquent
 */
class Todo extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'content','priority','difficulty','weight','category','project',
    ];
}

source/app/Http/Controllers/TodoController.php
<?php

namespace App\Http\Controllers;

use App\Todo;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use App\Repositories\DataReader;

class TodoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        Log::debug('TodoController::index()');
        $todos = DataReader::getUndoneTodos();
        $dones = DataReader::getDoneTodos();
        return view('todos.index', compact('todos', 'dones'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $todo = new Todo;
        $todo->content = $request["content"];
        $todo->priority = $request["priority"];
        $todo->difficulty = $request["difficulty"];
        $todo->weight = $request["weight"];
        $todo->category = $request["category"];
        $todo->project = $request["project"];
        $todo->save();

        return $this->getListsJson();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Todo  $todo
     * @return \Illuminate\Http\Response
     */
    public function show(Todo $todo)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Todo  $todo
     * @return \Illuminate\Http\Response
     */
    public function edit(Todo $todo)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Todo  $todo
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Todo $todo)
    {
        //$todo = Todo::find($todo);
        /*
        $todo->content = $request["content"];
        $todo->priority = $request["priority"];
        $todo->difficulty = $request["difficulty"];
        $todo->weight = $request["weight"];
        $todo->category = $request["category"];
        $todo->project = $request["project"];
        $todo->save();*/
        $todo->update($request->all());

        return $this->getListsJson();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Todo $todo
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Todo $todo)
    {
        // remove
        $todo->delete();

        return $this->getListsJson();
    }

    public function done(Todo $todo)
    {
        // mark as done
        $todo = Todo::find($todo->id);
        $todo->done_date =  now("UTC");
        $todo->save();

        return $this->getListsJson();
    }

    public function undone(Todo $todo)
    {
        // revert mark as done
        $todo = Todo::find($todo->id);
        $todo->done_date =  null;
        $todo->save();

        return $this->getListsJson();
    }

    private function getListsJson() {
        return response()->json(array(
            'todos' => DataReader::getUndoneTodos(),
            'dones' => DataReader::getDoneTodos(),
        ));
    }
}

source/resources/views/todos/index.blade.php
@extends('desktop.base')

@push('meta')
    <title>{{config('app.name')}} - Todo</title>
    <meta name="description" content="To-do list">
@endpush

@push('style')
    <link href="/css/todos.css" rel="stylesheet">
@endpush

@section('content')
    <div class="todosBlock">

        <div id="message"></div>
        <br>

        <button onclick="todoAdd('new task')" type="submit">Add</button>
        <br>

        <div id="todos">
            <table class="todosTable">
                @foreach($todos as $todo)
                    <tr>
                        <td>
                            <input class="todoContent" type="text" id="todoContent{{$todo->id}}" value="{{$todo->content}}">
                        </td>
                        <td class="smallestCell">
                            <button onclick="todoSave({{$todo->id}})" type="submit">Save</button>
                        </td>
                        <td class="smallestCell">
                            <button onclick="todoDone({{$todo->id}})" type="submit">Done</button>
                        </td>
                        <td class="smallestCell">
                            <button onclick="todoDestroy({{$todo->id}})" type="submit">Remove</button>
                        </td>
                    </tr>
                @endforeach
            </table>
        </div>

        <br><br>

        <div id="dones">
            <table class="todosTable">
                @foreach($dones as $todo)
                    <tr>
                        <td>
                            {{$todo->content}}
                        </td>
                        <td class="smallestCell">
                            {{$todo->done_date}}
                        </td>
                        <td class="smallestCell">
                            <button onclick="todoDone({{$todo->id}})" type="submit">Undo</button>
                        </td>
                        <td class="smallestCell">
                            <button onclick="todoDestroy({{$todo->id}})" type="submit">Remove</button>
                        </td>
                    </tr>
                @endforeach
            </table>
        </div>

    </div>


    <script>

        function generateTodosHtml(todos) {
            if (typeof todos === 'undefined') return "";
            let html = '<table class="todosTable">';
            for(let i = 0; i < todos.length; ++i) {
                html += '<tr>\n' +
                    '                    <td>\n' +
                    '                        <input class="todoContent" type="text" id="todoContent'+todos[i].id+'" value="'+todos[i].content+'">\n' +
                    '                    </td>\n' +
                    '                    <td class="smallestCell">\n' +
                    '                        <button onclick="todoSave('+todos[i].id+')" type="submit">Save</button>\n' +
                    '                    </td>\n' +
                    '                    <td class="smallestCell">\n' +
                    '                        <button onclick="todoDone('+todos[i].id+')" type="submit">Done</button>\n' +
                    '                    </td>\n' +
                    '                    <td class="smallestCell">\n' +
                    '                        <button onclick="todoDestroy('+todos[i].id+')" type="submit">Remove</button>\n' +
                    '                    </td>\n' +
                    '                </tr>';
            }
            html += '</table>';
            return html;
        }

        function generateDonesHtml(todos) {
            if (typeof todos === 'undefined') return "";
            let html = '<table class="todosTable">';
            for(let i = 0; i < todos.length; ++i) {
                html += '<tr>\n' +
                    '                    <td>\n' +
                                            todos[i].content+'\n' +
                    '                    </td>\n' +
                    '                    <td class="smallestCell">\n' +
                                            todos[i].done_date+'\n' +
                    '                    </td>\n' +
                    '                    <td class="smallestCell">\n' +
                    '                        <button onclick="todoUndo('+todos[i].id+')" type="submit">Undo</button>\n' +
                    '                    </td>\n' +
                    '                    <td class="smallestCell">\n' +
                    '                        <button onclick="todoDestroy('+todos[i].id+')" type="submit">Remove</button>\n' +
                    '                    </td>\n' +
                    '                </tr>';
            }
            html += '</table>';
            return html;
        }

        function todoDone(id) {
            let url = '{!! route('todos.done', ':id') !!}';
            url = url.replace(':id', id);
            let xhr = getXMLHttpRequest('GET', url);
            xhr.onload = function() {
                refreshFromResponse(xhr);
            };
            xhr.send();
        }

        function todoUndo(id) {
            let url = '{!! route('todos.undone', ':id') !!}';
            url = url.replace(':id', id);
            let xhr = getXMLHttpRequest('GET', url);
            xhr.onload = function() {
                refreshFromResponse(xhr);
            };
            xhr.send();
        }

        function todoDestroy(id) {
            let url = '{!! route('todos.destroy', ':id') !!}';
            url = url.replace(':id', id);
            let xhr = getXMLHttpRequest('DELETE', url);
            xhr.onload = function() {
                refreshFromResponse(xhr);
            };
            xhr.send(null);
        }

        function todoAdd(content) {
            let url = '{!! route('todos.store') !!}';
            let xhr = getXMLHttpRequest('POST', url);
            xhr.onload = function() {
                refreshFromResponse(xhr);
            };
            xhr.send(encodeURI('content=' + content));
        }

        function todoSave(id) {
            let content = document.getElementById("todoContent"+id).value;
            let url = '{!! route('todos.update', ':id') !!}';
            url = url.replace(':id', id);
            let xhr = getXMLHttpRequest('PUT', url);
            xhr.onload = function() {
                refreshFromResponse(xhr);
            };
            xhr.send(encodeURI('content=' + content));
        }

        function refreshFromResponse(xhr) {
            if (xhr.status === 200) {
                /* Refresh todos*/
                let response = JSON.parse(xhr.responseText);
                document.getElementById("todos").innerHTML = generateTodosHtml(response.todos);
                document.getElementById("dones").innerHTML = generateDonesHtml(response.dones);
            }
            else {
                displayMessage("Sorry, an error occurred. Check your Internet connection and try again.");
                console.error(xhr.responseText);
            }
        }
    </script>

@endsection